config/routes.rb
DNSAdmin::Application.routes.draw do
  resources :nagios_statuses

  netzke

  root :to => "tasks#list"
  get "tasks/list"

  get "dns/test"
  get "dns/index"

  get "nconf/list"
  get "nconf/wp"
  get "nconf/wproxy"
  get "nconf/wxs"
  get "nconf/dns"
  get "nconf/websites"

end

app/controllers/nagios_statuses_controller.rb
class NagiosStatusesController < ApplicationController
  layout false
  # GET /nagios_statuses
  # GET /nagios_statuses.json
  def index
    @nagios_statuses = NagiosStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nagios_statuses }
    end
  end

  # GET /nagios_statuses/1
  # GET /nagios_statuses/1.json
  def show
    @nagios_status = NagiosStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nagios_status }
    end
  end

  # GET /nagios_statuses/new
  # GET /nagios_statuses/new.json
  def new
    @nagios_status = NagiosStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nagios_status }
    end
  end

  # GET /nagios_statuses/1/edit
  def edit
    @nagios_status = NagiosStatus.find(params[:id])
  end

  # POST /nagios_statuses
  # POST /nagios_statuses.json
  def create
    monitor_ip = request.env['HTTP_X_REAL_IP'] || request.remote_addr
    monitor = Host.find_by_ip(monitor_ip)

    case params[:object_type]
    when "service"
      @app_service = AppService.find(params[:app_service][:id])
      nagios_status = params[:nagios_status]
      unless monitor.nil?
        nagios_status[:monitor_id] = monitor.id
      end

      @app_service.nagios_statuses.create(nagios_status)

      render :inline => "ok! monitor_ip " + monitor_ip
    else
      render :inline => "unknown object typ emonitor_ip " + monitor_ip
    end

#    @nagios_status = NagiosStatus.new(params[:nagios_status])

#    respond_to do |format|
#      if @nagios_status.save
#        format.html { redirect_to @nagios_status, notice: 'Nagios status was successfully created.' }
#        format.json { render json: @nagios_status, status: :created, location: @nagios_status }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @nagios_status.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /nagios_statuses/1
  # PUT /nagios_statuses/1.json
  def update
    @nagios_status = NagiosStatus.find(params[:id])

    respond_to do |format|
      if @nagios_status.update_attributes(params[:nagios_status])
        format.html { redirect_to @nagios_status, notice: 'Nagios status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nagios_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nagios_statuses/1
  # DELETE /nagios_statuses/1.json
  def destroy
    @nagios_status = NagiosStatus.find(params[:id])
    @nagios_status.destroy

    respond_to do |format|
      format.html { redirect_to nagios_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nagios_statuses_helper.rb
module NagiosStatusesHelper
end

app/views/nagios_statuses/_form.html.erb
<%= form_for(@nagios_status) do |f| %>
  <% if @nagios_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nagios_status.errors.count, "error") %> prohibited this nagios_status from being saved:</h2>

      <ul>
      <% @nagios_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :statusable %><br />
    <%= f.text_field :statusable %>
  </div>
  <div class="field">
    <%= f.label :monitor %><br />
    <%= f.text_field :monitor %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br />
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :event_status %><br />
    <%= f.text_field :event_status %>
  </div>
  <div class="field">
    <%= f.label :event_message %><br />
    <%= f.text_field :event_message %>
  </div>
  <div class="field">
    <%= f.label :event_time %><br />
    <%= f.datetime_select :event_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nagios_statuses/create.html.erb
<%= @app_service %>

app/views/nagios_statuses/edit.html.erb
<h1>Editing nagios_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @nagios_status %> |
<%= link_to 'Back', nagios_statuses_path %>

app/views/nagios_statuses/index.html.erb
<h1>Listing nagios_statuses</h1>

<table>
  <tr>
    <th>Statusable</th>
    <th>Monitor</th>
    <th>Event type</th>
    <th>Event status</th>
    <th>Event message</th>
    <th>Event time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nagios_statuses.each do |nagios_status| %>
  <tr>
    <td><%= nagios_status.statusable_type %></td>
    <td><%= nagios_status.monitor %></td>
    <td><%= nagios_status.event_type %></td>
    <td><%= nagios_status.event_status %></td>
    <td><%= nagios_status.event_message %></td>
    <td><%= nagios_status.created_at %></td>
    <td><%= link_to 'Show', nagios_status %></td>
    <td><%= link_to 'Edit', edit_nagios_status_path(nagios_status) %></td>
    <td><%= link_to 'Destroy', nagios_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nagios status', new_nagios_status_path %>

app/views/nagios_statuses/new.html.erb
<h1>New nagios_status</h1>

<%= render 'form' %>

<%= link_to 'Back', nagios_statuses_path %>

app/views/nagios_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Statusable:</b>
  <%= @nagios_status.statusable %>
</p>

<p>
  <b>Monitor:</b>
  <%= @nagios_status.monitor %>
</p>

<p>
  <b>Event type:</b>
  <%= @nagios_status.event_type %>
</p>

<p>
  <b>Event status:</b>
  <%= @nagios_status.event_status %>
</p>

<p>
  <b>Event message:</b>
  <%= @nagios_status.event_message %>
</p>

<p>
  <b>Event time:</b>
  <%= @nagios_status.event_time %>
</p>


<%= link_to 'Edit', edit_nagios_status_path(@nagios_status) %> |
<%= link_to 'Back', nagios_statuses_path %>