config/routes.rb
DNSAdmin::Application.routes.draw do
  resources :nagios_statuses

  netzke

  root :to => "tasks#list"
  get "tasks/list"

  get "dns/test"
  get "dns/index"

  get "nconf/list"
  get "nconf/wp"
  get "nconf/wproxy"
  get "nconf/wxs"
  get "nconf/dns"
  get "nconf/websites"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", "#", id: "logo" %>
      <nav>
      <ul class="nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "DNS", dns_index_path %></li>
      </ul>
        <ul class="nav pull-right">
          <li><%= link_to "Home", "#" %></li>
          <% if @signed_in %>
          <li><%= link_to "Users", "#" %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "#" %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", "#", method: "delete" %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Sign in", "#" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= load_netzke %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>